### ISSUE TITLE
received proxy error - could not repeat

### ISSUE THREAD

**Issue by satra** [OpenNeuroLab/BrainBox#102]
![image](https://cloud.githubusercontent.com/assets/184063/20044230/0760edae-a465-11e6-9d26-586444fd65f0.png)

**Comment by r03ert0** [comment]
maybe the server was offline or restarting? Do you know how to reproduce the bug?

**Comment by r03ert0** [comment]
now there's progressive, client-triggered loading of user's lists of mri files, annotations and projects. Additionally, MRI download at the server is non blocking. I'll close the issue.
