### ISSUE TITLE
not urgent! deleting project: expected behaviour: empty project settings page

### ISSUE THREAD

**Issue by katjaq** [OpenNeuroLab/BrainBox#103]
for the moment, it just says 'successfully deleted' but all my list of MRIs is still fully there;
only on refresh I get the empty page BUT this empty page is still called project/MyProjectName after refresh! 
http://brainbox.pasteur.fr/project/NIHPD2/settings -- just empty; I would expect it to jump back to the 'create new project window http://brainbox.dev/project/new ((or to the homepage))

**Comment by r03ert0** [comment]
Fixed by commit 88e085f
