### ISSUE TITLE
I can view files that I think I should not be able to

### ISSUE THREAD

**Issue by leiliew** [OpenNeuroLab/BrainBox#120]
In testing with Katja, I (leiliew) found that I can view the NIHPD2 dataset even though I shouldn't have permission to do so.

**Comment by r03ert0** [comment]
That's a bug... can you describe how you did it?

**Comment by r03ert0** [comment]
I see what you mean: If you know the URL for a project, even if you are not logged in, you are able to get into it. Not into the project settings, but yes into the project page.
