### ISSUE TITLE
brainbox homepage is completely unintuitive to naive brain researchers who land there

### ISSUE THREAD

**Issue by satra** [OpenNeuroLab/BrainBox#131]
@r03ert0 - i'll be working on improving landing pages for openneuro and metasearch. 

we need to do something about brainbox landing page as well. here are some feedback from some users:

1. the home page has no information on what the user is supposed to do
2. the arrows don't work
3. recently visited is empty for the new user

**Comment by r03ert0** [comment]
1. it's true. At some point I was concerned about the clutter of the home page in smartphones, and then split the home page into pages. But it's probably too much. I like what you did with intro.js in metasearch. I think the solution goes that way: a balance between simplification and explicit guidance. I'll work on that.

2. Which arrows?

3. For a new user recently visited is replaced by "Some brains to try", where there are 5 example brains. You need to clear the website's localStorage object to see it.

**Comment by satra** [comment]
one the front page the double arrows that are at the bottom center of the page. (the same arrows exist in openneu.ro, but are clickable and use scrolly to get to the next page).

perhaps you can combine some brains to try and the enter a URL into a single page (similar to ted's design)

**Comment by r03ert0** [comment]
we talked with ted about having close to the Go button a "Take me to a brain" drop down menu with a list of brains to try... that would have a small footprint and contain a lot of information

**Comment by satra** [comment]
i think visibility is good to (so for example having thumbnails of 3D renders showing different types of brains.

**Comment by r03ert0** [comment]
description paragraph brought back; list of brains to try added as drop down menu
