### ISSUE TITLE
nifti orientation not being read correctly

### ISSUE THREAD

**Issue by satra** [OpenNeuroLab/BrainBox#133]
example:

http://brainbox.pasteur.fr/mri/?url=https://s3.amazonaws.com/fcp-indi/data/Projects/BrainGenomicsSuperstructProject/orig_bids/sub-1000/ses-01/anat/sub-1000_ses-01_T1w.nii.gz&view=sag&slice=96

**Comment by r03ert0** [comment]
I'll try to see what makes that some files are read right and some wrong.

__List of test files__

Read right:

Read wrong:
https://s3.amazonaws.com/fcp-indi/data/Projects/BrainGenomicsSuperstructProject/orig_bids/sub-1000/ses-01/anat/sub-1000_ses-01_T1w.nii.gz
https://s3.amazonaws.com/fcp-indi/data/Projects/ACPI/RawData/uci_1/0028147/session_1/anat_1/anat.nii.gz

It seems that the error only happens with .nii files. I'll convert the wrongly read .nii files to mgz to check that the orientation matrix is the same.

**Comment by r03ert0** [comment]
Transformation matrices:

Right
1.
Q-Form Code = 1
S-Form Code = 1
Quaternion Parameters:  b = -0.5  c = 0.5  d = -0.5
Quaternion Offsets:  x = -97.1253  y = 168.71899  z = 134.5
S-Form Parameters X: 0.0, 0.0, 1.2, -97.1253
S-Form Parameters Y: -1.0, 0.0, 0.0, 168.71899
S-Form Parameters Z: 0.0, -1.0, 0.0, 134.5

2.
Q-Form Code = 1
S-Form Code = 1
Quaternion Parameters:  b = -0.5  c = 0.5  d = -0.5
Quaternion Offsets:  x = -101.694  y = 161.256  z = 128.45599
S-Form Parameters X: 0.0, 0.0, 1.2, -101.694
S-Form Parameters Y: -1.0, 0.0, 0.0, 161.256
S-Form Parameters Z: 0.0, -1.0, 0.0, 128.45599

3.
Q-Form Code = 1
S-Form Code = 1
Quaternion Parameters:  b = -0.5  c = 0.5  d = -0.5
Quaternion Offsets:  x = -99.9378  y = 160.75  z = 131.21899
S-Form Parameters X: 0.0, 0.0, 1.2, -99.9378
S-Form Parameters Y: -1.0, 0.0, 0.0, 160.75
S-Form Parameters Z: 0.0, -1.0, 0.0, 131.21899

Wrong:
4.
5.
6.
7.
8.

**Comment by r03ert0** [comment]
The mapping between volume coordinates and screen coordinates is now built directly, without passing through the world coordinates. Each column of the volume-to-world rotation matrix is read to determine to which screen coordinate maps each volume coordinate.
