### ISSUE TITLE
White text on white background in new project title entry field

### ISSUE THREAD

**Issue by Shotgunosine** [OpenNeuroLab/BrainBox#147]
On the create a new project screen, the text field for entering the name of the project has a white background, and the text defaults to white, so it is difficult to know if you've entered anything at all. Issue observed running Mac OSX 10.10.5 from Chrome 57.0.2987.133 (64-bit) and Safari Version 10.1 (10603.1.30.0.34).

**Comment by katjaq** [comment]
thank you very much for the note! 
fixed :)
