### ISSUE TITLE
nibabel cannot open downloaded aseg.nii.gz from brainbox

### ISSUE THREAD

**Issue by satra** [OpenNeuroLab/BrainBox#151]
use any adhd200 participant and download a freesurfer annotation.

**Comment by satra** [comment]
downloaded by clicking on download

**Comment by r03ert0** [comment]
Hi Satra,

I just pushed a fix for the client-side Nifti exporting. I downloaded an aseg from an ADHD200 subject, and it opened correctly with mango and nibabel. Could you give it a try? I'll close the issue

**Comment by satra** [comment]
looks good. thanks!
