### ISSUE TITLE
Set up Mocha for testing the code, and puppeteer or selenium for the UI?

### ISSUE THREAD

**Issue by r03ert0** [OpenNeuroLab/BrainBox#157]
### Is this a feature request or a bug report? 
Enhancement request

### What is the current behaviour?
There's no testing suite for brainbox...

### What is the expected or desired behaviour?
To start a testing suite using mocha.js for testing the code, and possibly puppeteer or selenium for testing the UI

**Comment by iain8** [comment]
@r03ert0 I can get this set up with some tasty testing.
