### ISSUE TITLE
add eslint to BrainBox

### ISSUE THREAD

**Issue by katjaq** [OpenNeuroLab/BrainBox#158]
### What is the current behaviour?
BrainBox does not yet have any test for achieving and maintaining a common code style.

### What is the expected or desired behaviour?
We would like to use eslint on our files to adapt our code to common standards and make it easier for anyone to jump on board and work with us.

**Comment by jhia** [comment]
Can I help you with this?

**Comment by omgitsjoao** [comment]
What about using [xo](https://github.com/sindresorhus/xo) ?
Its easy to setup, uses eslint and  come with predefined rules

**Comment by r03ert0** [comment]
sounds good!

**Comment by Danielsilveira98** [comment]
Do would you use eslint in grunt?

**Comment by katjaq** [comment]
what is the advantage compared with pure eslint or xo?

**Comment by omgitsjoao** [comment]
@Danielsilveira98  @katjaq  Grunt is not useful here right now, you got everything covered on the npm scripts.

**Comment by jhia** [comment]
@katjaq I think using xo means more dependencies but covers a lot of work configuring pure eslint. While eslint standalone needs to be configured for tests and others.

**Comment by katjaq** [comment]
Thank you very much for your replies! 
Last week-end, we started trying eslint on one of our projects ([MicroDraw](https://github.com/r03ert0/microdraw)). We started with >2500 eslint errors ÖÖ and then started adding the .eslintrc file. 

Maybe you could reuse these files and give a try to eslint? That would be nice.

**Comment by omgitsjoao** [comment]
Well, xo gives a widely accepted defaults, so you don't need an eslintrc
file, also it can't fixe common mistakes with just a command. But if you
want to use bare eslint you can have a default rc file to all the
repositories.

Oh btw xo uses eslint under the hood, so you can customize it the same way
you do with eslint

**Comment by katjaq** [comment]
ok!!! 😃  You made me all curious!! would you like to set it up with xo? I would like to give it a try and what you say sounds good!!

Thank you so much!!! looking forward to your pull request!! \\ö//

**Comment by omgitsjoao** [comment]
No problem at all!!
I'm working on it! I'll leave the fix magic to you 😸
