### ISSUE TITLE
header of nifti file generated by BrainBox is missing some little piece of information

### ISSUE THREAD

**Issue by katjaq** [OpenNeuroLab/BrainBox#160]
### Is this a feature request or a bug report? 
bug report

### What is the current behaviour?
When a mask is downloaded from BrainBox (either with curl or via the download button), the nifit file can be opened by some programs, like FSL for instance, and by some others not (loading with nibabel fails). For example the "Default" mask that you can download by clicking on the download link in this page <http://brainbox.pasteur.fr/mri?url=https://dl.dropbox.com/sh/71jbelduefu41xs/AADysls57HwmJT0pdbbSVI4Na/case_001_2.nii.gz>

 A pass through FSL's ```fslchfiletype NIFTI_GZ``` can fix it. 
We should look at the header when the file comes from BrainBox and compare it to the one after passing it through FSL and add the missing little thing to the BrainBox code.

### What is the expected or desired behaviour?
The nifti file works fine for all of our analyses that we do after passing it through fslchfiletype. This step should not be necessary but BrainBox should generate all necessary header fields.

**Comment by r03ert0** [comment]
should be fixed by the commit
