### ISSUE TITLE
color-picker tool

### ISSUE THREAD

**Issue by r03ert0** [OpenNeuroLab/BrainBox#27]
a color-picker tool: click on a segmentation colour will set that as the current colour. It also displays the name of the region (ex., Left Accumbens). Additionally, the currently selected colour (region) in the colour-selector window should be indicated (by a border?)

**Comment by katjaq** [comment]
started working on it in 'eyedropper' branch;
for the moment only working for freesurfer 48 segmentations

**Comment by r03ert0** [comment]
added to master by pull request #47
