### ISSUE TITLE
Replace links with titles in "some brains to try" section

### ISSUE THREAD

**Issue by amyleesterling** [OpenNeuroLab/BrainBox#28]
Say "lion brain" or "human brain" 

--> Add a link to 3D view mode of completed human brain

![image](https://cloud.githubusercontent.com/assets/1858187/17496248/64d28a32-5d8a-11e6-9b4e-ecc8bdccdc54.png)

**Comment by r03ert0** [comment]
done.
mri dataset titles appear now in a dropdown menu called 'a list of brains to try' in the home page
