### ISSUE TITLE
add ‘public’ back to the 'access' field for project settings/project creation

### ISSUE THREAD

**Issue by katjaq** [OpenNeuroLab/BrainBox#39]
lets add ‘public’ back to the 'access' field for project settings/project creation, with the default settings for an ‘open project’, and otherwise users must change the access rights of ‘public’ , but this line should never disappear (no [-]delete option functionality for this always first line in the access area), so that users will always be reminded of the access rights for public and might make their project open eventually very easily : )

**Comment by r03ert0** [comment]
added a configurable 'anyone' user in pull request #49
