### ISSUE TITLE
UI needs to be fixed for project page

### ISSUE THREAD

**Issue by satra** [OpenNeuroLab/BrainBox#59]
for both csv upload and after upload the UI doesn't handle long URLs.

![image](https://cloud.githubusercontent.com/assets/184063/19406721/6b1f0bf0-9259-11e6-9cf3-76b2555ef4c8.png)

**Comment by r03ert0** [comment]
satra, could you check if the display bug is still there?

**Comment by satra** [comment]
this is now good for both.
