### ISSUE TITLE
payload too large for csv upload

### ISSUE THREAD

**Issue by satra** [OpenNeuroLab/BrainBox#60]
![image](https://cloud.githubusercontent.com/assets/184063/19406727/9e938614-9259-11e6-890a-40a82f5afe65.png)

possible solution here depending on how express is being used:

http://stackoverflow.com/questions/19917401/node-js-express-request-entity-too-large

**Comment by satra** [comment]
happens during POST:

![image](https://cloud.githubusercontent.com/assets/184063/19406738/fab0f29c-9259-11e6-8fc2-65ce71074a19.png)

**Comment by katjaq** [comment]
Hey Satra, could you send me the csv file you were trying to upload for ABIDE-I so we could have a look and fix the bug? thank you! :)

**Comment by katjaq** [comment]
csv upload fixed, 
max set to 50MB
