### ISSUE TITLE
track IXI dataset

### ISSUE THREAD

**Issue by satra** [OpenNeuroLab/BrainBox#68]
make available the ixi dataset as part of brainbox.

**Comment by r03ert0** [comment]
what's the ixi dataset?

**Comment by satra** [comment]
http://brain-development.org/ixi-dataset/

**Comment by satra** [comment]
i wrote to daniel rueckert to see if he will untar it himself.

**Comment by r03ert0** [comment]
If that can help, I have a script to batch-upload individual files to
zenodo. You can then get an individual for each of them.

**Comment by r03ert0** [comment]
ixi dataset project is added
