### ISSUE TITLE
csv upload should respect a standard csv

### ISSUE THREAD

**Issue by satra** [OpenNeuroLab/BrainBox#71]
csv parser should use `','` by default instead of `', '`

**Comment by r03ert0** [comment]
we could use [ ]*,[ ]* just in case

**Comment by satra** [comment]
@r03ert0 - sounds good.

here is a csv parser you can use: https://github.com/mholt/PapaParse

**Comment by r03ert0** [comment]
I'm splitting columns based on the regex expression. If we need something more sophisticate, we can add the papaparse library
