### ISSUE TITLE
add 'go to project' button on project settings page

### ISSUE THREAD

**Issue by katjaq** [OpenNeuroLab/BrainBox#80]
for the moment, I always delete /settings from the browser line

**Comment by satra** [comment]
should be able to just click on the project name.

**Comment by katjaq** [comment]
yes, you are right, it would be ideal to just click on the project name to get to the project page! :) we have to think about that. at the moment the users type the title of their project there… so when you click on the name, you can edit it, don’t know where/how to link to the project page then; 
or how to change the title-editing if we make the title a link, respectively ...

**Comment by katjaq** [comment]
added to project avatar as well as to project short name in commit de63a48
