### ISSUE TITLE
need to test: can you replace names on csv upload?

### ISSUE THREAD

**Issue by satra** [OpenNeuroLab/BrainBox#92]

**Comment by satra** [comment]
csv import does not override names.

**Comment by r03ert0** [comment]
should it?

**Comment by satra** [comment]
if it's the owner, i think there should be a choice or by default acceptance.

**Comment by satra** [comment]
for us the ID is still the MRI (or it's hash??)

for example, for all the MRIs i uploaded from fcp on amazon, the URLs are going to change. we need to have a system where an MRI can have multiple locations as long as the hash is the same.

**Comment by satra** [comment]
this will also allow us to know when duplicates are being added and reduce redundancy.

so for this thread:

MRI should append URLs if hash same
names: i think should be replaced within a project.

an MRI itself can be associated with many projects and therefore have different names in them.

**Comment by r03ert0** [comment]
there's always the risk of overwriting what some other person did... Maybe
we can provide feedback on which names present conflicts and let the user
decide

**Comment by r03ert0** [comment]
existing names are now overwriten by imported names
